name: Deploy to Vultr

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.VULTR_SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.VULTR_KNOWN_HOSTS }}

    - name: Install rsync
      run: sudo apt-get update && sudo apt-get install -y rsync

    - name: Deploy to Vultr
      env:
        VULTR_HOST: ${{ secrets.VULTR_HOST }}
        VULTR_USER: ${{ secrets.VULTR_USER }}
        PROJECT_PATH: /root/projects/mortgage-calculator
      run: |
        # Sync files to the server, excluding .git and lock files
        rsync -avz --delete --exclude='.git' --exclude='*.lock' ./ $VULTR_USER@$VULTR_HOST:$PROJECT_PATH/

        # SSH into the server and execute commands
        ssh $VULTR_USER@$VULTR_HOST << EOF
          cd $PROJECT_PATH
          docker-compose down
          docker-compose build
          docker-compose up -d
        EOF